package com.example.exception.trycatch;

public class TryCatchDemo {
	
	public void add(int a, int b) {
		int c = a+b;
		
		System.out.println("Addition of a and b : "+c);
	}

	public void div(int a, int b) {
		int c = a/b;
		
		System.out.println("Division of a and b : "+c);
	} 
	
	public void multi(int a, int b) {
		int c = a*b;
		
		System.out.println("Multiplication of a and b : "+c);
	}
	
	public static void main(String[] args) {

		TryCatchDemo tryCatchDemo = new TryCatchDemo();
		
		tryCatchDemo.add(10,20);
		tryCatchDemo.div(12, 0);
		tryCatchDemo.multi(5,2);

	}

}
